In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sns

# Loading the dataset

In [10]:
data=pd.read_csv('EmployeeAttrition.csv')

In [11]:
data.head()

Education JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0        College           High         2            1102              5993.0   
1  Below College         Medium         2             279              5130.0   
2        College         Medium         1            1373              2090.0   
3         Master           High         1            1392              2909.0   
4  Below College           High         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

  PerformanceRating Attrition  
0         Excellent       Yes  
1       Outstanding        No  
2         Excellent       Yes  
3         Excellent        No  
4         Excellent        No

In [12]:
data.shape

(1470, 14)

In [22]:
data.describe()

JobLevel  DailyRate(USD)  MonthlyIncome(USD)  NoofCompaniesWorked  \
count  1470.000000     1470.000000         1470.000000          1470.000000   
mean      2.063946      802.485714         6499.438776             2.693197   
std       1.106940      403.509100         4704.700497             2.498009   
min       1.000000      102.000000         1009.000000             0.000000   
25%       1.000000      465.000000         2914.750000             1.000000   
50%       2.000000      802.000000         4919.000000             2.000000   
75%       3.000000     1157.000000         8368.500000             4.000000   
max       5.000000     1499.000000        19999.000000             9.000000   

       TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
count        1470.000000     1470.000000         1470.000000   
mean           11.279592        7.008163            4.229252   
std             7.780782        6.126525            3.623137   
min             0.000000        0.000000            0.000000   
25%             6.000000        3.000000            2.000000   
50%            10.000000        5.000000            3.000000   
75%            15.000000        9.000000            7.000000   
max            40.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  
count              1470.000000              1470.000000            1470.000000  
mean                  2.187755                 4.123129               2.799320  
std                   3.222430                 3.568136               1.289271  
min                   0.000000                 0.000000               0.000000  
25%                   0.000000                 2.000000               2.000000  
50%                   1.000000                 3.000000               3.000000  
75%                   3.000000                 7.000000               3.000000  
max                  15.000000                17.000000               6.000000

# Continuous and Categorical information

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Education                1470 non-null   object 
 1   JobInvolvement           1466 non-null   object 
 2   JobLevel                 1470 non-null   int64  
 3   DailyRate(USD)           1470 non-null   int64  
 4   MonthlyIncome(USD)       1466 non-null   float64
 5   NoofCompaniesWorked      1470 non-null   int64  
 6   TotalWorkingYears        1470 non-null   int64  
 7   YearsAtCompany           1470 non-null   int64  
 8   YearsInCurrentRole       1470 non-null   int64  
 9   YearsSinceLastPromotion  1470 non-null   int64  
 10  YearsWithCurrentManager  1470 non-null   int64  
 11  TrainingTimesLastYear    1470 non-null   int64  
 12  PerformanceRating        1470 non-null   object 
 13  Attrition                1470 non-null   object 
dtypes: float64(1), int64(9),

# Finding the null values

In [15]:
data.isnull().sum()

Education                  0
JobInvolvement             4
JobLevel                   0
DailyRate(USD)             0
MonthlyIncome(USD)         4
NoofCompaniesWorked        0
TotalWorkingYears          0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrentManager    0
TrainingTimesLastYear      0
PerformanceRating          0
Attrition                  0
dtype: int64

In [17]:
data['JobInvolvement'].mode()

0    High
dtype: object

In [19]:
data['JobInvolvement'] =data['JobInvolvement'].fillna(data['JobInvolvement'].mode()[0])

In [23]:
data['MonthlyIncome(USD)'] =data['MonthlyIncome(USD)'].fillna(data['MonthlyIncome(USD)'].mean())

In [24]:
data.isnull().sum()

Education                  0
JobInvolvement             0
JobLevel                   0
DailyRate(USD)             0
MonthlyIncome(USD)         0
NoofCompaniesWorked        0
TotalWorkingYears          0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrentManager    0
TrainingTimesLastYear      0
PerformanceRating          0
Attrition                  0
dtype: int64

# Label Encoding

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Education']=le.fit_transform(data['Education'])
data['JobInvolvement']=le.fit_transform(data['JobInvolvement'])
data['PerformanceRating']=le.fit_transform(data['PerformanceRating'])
data['Attrition']=le.fit_transform(data['Attrition'])

In [26]:
data.head()

Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               2         2             279              5130.0   
2          2               2         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

   PerformanceRating  Attrition  
0                  0          1  
1                  1          0  
2                  0          1  
3                  0          0  
4                  0          0

# Independent and Dependent

In [29]:
x=data.iloc[:,0:13]
x.head()


Education  JobInvolvement  JobLevel  DailyRate(USD)  MonthlyIncome(USD)  \
0          2               0         2            1102              5993.0   
1          1               2         2             279              5130.0   
2          2               2         1            1373              2090.0   
3          4               0         1            1392              2909.0   
4          1               0         1             591              3468.0   

   NoofCompaniesWorked  TotalWorkingYears  YearsAtCompany  YearsInCurrentRole  \
0                    8                  8               6                   4   
1                    1                 10              10                   7   
2                    6                  7               0                   0   
3                    1                  8               8                   7   
4                    9                  6               2                   2   

   YearsSinceLastPromotion  YearsWithCurrentManager  TrainingTimesLastYear  \
0                        0                        5                      0   
1                        1                        7                      3   
2                        0                        0                      3   
3                        3                        0                      3   
4                        2                        2                      3   

   PerformanceRating  
0                  0  
1                  1  
2                  0  
3                  0  
4                  0

In [30]:
y=data.iloc[:,[13]]
y.head()

Attrition
0          1
1          0
2          1
3          0
4          0

# Train Test Split

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1176, 13)
(1176, 1)
(294, 13)
(294, 1)


# Feature Selection

In [33]:
from sklearn.feature_selection import mutual_info_classif
mi=mutual_info_classif(x_train,y_train)
mi

C:\Users\asus\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([0.        , 0.00396493, 0.03810369, 0.01529794, 0.04186989,
       0.        , 0.02917994, 0.03375602, 0.02143501, 0.        ,
       0.03828122, 0.        , 0.01438702])

In [34]:
MI=pd.Series(mi)
MI.index=x_train.columns
MI.sort_values(ascending=False)

MonthlyIncome(USD)         0.041870
YearsWithCurrentManager    0.038281
JobLevel                   0.038104
YearsAtCompany             0.033756
TotalWorkingYears          0.029180
YearsInCurrentRole         0.021435
DailyRate(USD)             0.015298
PerformanceRating          0.014387
JobInvolvement             0.003965
Education                  0.000000
NoofCompaniesWorked        0.000000
YearsSinceLastPromotion    0.000000
TrainingTimesLastYear      0.000000
dtype: float64

# 1.Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(x_train,y_train)

C:\Users\asus\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [36]:
y_pred=logr.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_pred,y_test)

array([[245,  49],
       [  0,   0]], dtype=int64)

In [38]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.83      0.91       294
           1       0.00      0.00      0.00         0

    accuracy                           0.83       294
   macro avg       0.50      0.42      0.45       294
weighted avg       1.00      0.83      0.91       294



C:\Users\asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 2.Decision Tree

In [39]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [40]:
y_pred=dtc.predict(x_test)

In [41]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [42]:
confusion_matrix(y_pred,y_test)

array([[209,  38],
       [ 36,  11]], dtype=int64)

In [43]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       247
           1       0.22      0.23      0.23        47

    accuracy                           0.75       294
   macro avg       0.54      0.54      0.54       294
weighted avg       0.75      0.75      0.75       294



# 3.Random Forest

In [44]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)

<ipython-input-44-3872a98b0b86>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(x_train,y_train)


RandomForestClassifier()

In [45]:
y_test[:5]

Attrition
442           0
1091          0
981           1
785           0
1332          1

In [46]:
y_pred=rfc.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test,y_pred)

0.8231292517006803

In [48]:
confusion_matrix(y_test,y_pred)

array([[239,   6],
       [ 46,   3]], dtype=int64)

In [49]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.98      0.90       245
           1       0.33      0.06      0.10        49

    accuracy                           0.82       294
   macro avg       0.59      0.52      0.50       294
weighted avg       0.75      0.82      0.77       294



# 4.KNN

In [50]:
from sklearn.neighbors import KNeighborsClassifier

knn=KNeighborsClassifier()

knn.fit(x_train,y_train)

C:\Users\asus\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [51]:
y_pred=knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8197278911564626

In [53]:
y_train_pred=knn.predict(x_train)
y_train_pred

array([0, 0, 0, ..., 0, 0, 0])

In [54]:
accuracy_score(y_train,y_train_pred)

0.8579931972789115

In [55]:
from collections import Counter as c
c(y_test)

Counter({'Attrition': 1})

In [56]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[234  11]
 [ 42   7]]


In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix1 = confusion_matrix(y_train,y_train_pred)
print(confusion_matrix1)

[[961  27]
 [140  48]]


In [58]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90       245
           1       0.39      0.14      0.21        49

    accuracy                           0.82       294
   macro avg       0.62      0.55      0.55       294
weighted avg       0.77      0.82      0.78       294



# 5.SVM

In [59]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [60]:
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.svm import SVC 
svm = SVC() 
svm.fit(x_train, y_train) 

C:\Users\asus\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [61]:
y_pred = svm.predict(x_test)

In [62]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8333333333333334

In [63]:
y_pred_train=svm.predict(x_train)
accuracy_score(y_train,y_pred_train)

0.8401360544217688

In [64]:
y_train_pred=svm.predict(x_train)
y_train_pred

array([0, 0, 0, ..., 0, 0, 0])

In [65]:
accuracy_score(y_train,y_train_pred)

0.8401360544217688

In [66]:
from collections import Counter as c
c(y_test)

Counter({'Attrition': 1})

In [67]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[245   0]
 [ 49   0]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91       245
           1       0.00      0.00      0.00        49

    accuracy                           0.83       294
   macro avg       0.42      0.50      0.45       294
weighted avg       0.69      0.83      0.76       294



C:\Users\asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\asus\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 6.Naive Bayes

In [68]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()

nb.fit(x_train,y_train)

C:\Users\asus\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GaussianNB()

In [69]:
y_pred=nb.predict(x_test)
y_pred

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0])

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7312925170068028

In [71]:
y_train_pred=nb.predict(x_train)
y_train_pred

array([0, 1, 0, ..., 0, 1, 0])

In [72]:
accuracy_score(y_train,y_train_pred)

0.6938775510204082

In [73]:
from collections import Counter as c
c(y_test)

Counter({'Attrition': 1})

In [74]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[191  54]
 [ 25  24]]
              precision    recall  f1-score   support

           0       0.88      0.78      0.83       245
           1       0.31      0.49      0.38        49

    accuracy                           0.73       294
   macro avg       0.60      0.63      0.60       294
weighted avg       0.79      0.73      0.75       294



# Hyper Parameter Tuning

In [75]:
from sklearn.model_selection import GridSearchCV
grid_param={ 
    'criterion':['gini','entropy'],
    'max_depth' : [ 5,6,7] 
}
grid_search=GridSearchCV(estimator=dtc,param_grid=grid_param,cv=5,n_jobs=-1)
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 6, 7]})

In [76]:
grid_search.best_params_

{'criterion': 'entropy', 'max_depth': 5}

In [77]:
dtc_hyper=DecisionTreeClassifier(criterion='entropy',max_depth=5)
dtc_hyper.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [78]:
y_pred_hyper=dtc_hyper.predict(x_test)
accuracy_score(y_test,y_pred_hyper)

0.8231292517006803

In [79]:
confusion_matrix(y_pred,y_test)

array([[191,  25],
       [ 54,  24]], dtype=int64)

In [80]:
confusion_matrix(y_pred_hyper,y_test)

array([[238,  45],
       [  7,   4]], dtype=int64)